server.port=8084
spring.application.name=ai-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

jwt.secret=appverse_super_secret_key_2024_wipro

groq.api.key=grok-api-key